### PR TITLE
Header compatibility and templates structure

### PR DESCRIPTION
**Pull request by popovski2**
Added new folder structure for templates - different templates will be used for 2.9 and other ones for 2.10
After this merge, we can safely merge branch ckan-2.10-support into main

### CODE REVIEW

**Comment by gocemitevski** [comment]
We need to do more work to be able to merge this branch. There are things which are not implemented based on best practices and the local theme setup is quite messy. The code changes introduced with this PR will be reused at a later stage.

**Comment by gocemitevski** [comment]
Here are the changes we need to introduce:

- Remove gulp.js from the theme
- Restructure front-end CSS assets based on the official CKAN guidelines for Webassets:
  - https://docs.ckan.org/en/2.9/theming/css.html
  - https://docs.ckan.org/en/2.9/theming/webassets.html
- Remove deprecated files and clean code

**Comment by teodora-aleksovska** [comment]
@gocemitevski  please review these commits and let me know if you have any remarks

**Review by gocemitevski — CHANGES_REQUESTED** [review]
We need to fix the linting errors before we can merge this PR.

**Review by gocemitevski — APPROVED** [review]

**Pull request merged**
